security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                login_path: redirect_login
                success_handler: app_bundle.handler.authentication_success_handler
            logout:
                path: fos_user_security_logout
                success_handler: app_bundle.handler.logout_success_handler
            anonymous:    true

    access_control:
        - { path: ^/my/, role: ROLE_USER }
        - { path: ^/pl/moje/, role: ROLE_USER }