# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app_bundle.fosuser_redirect:
        class: AppBundle\EventListener\FOSUserRedirectListner
        arguments: ['@router', '@request_stack']
        tags:
            - { name: kernel.event_subscriber }
    app_bundle.handler.logout_success_handler:
        class: AppBundle\Handler\LogoutSuccessHandler
        arguments: ['@security.http_utils', '@request_stack']
        tags:
            - { name: monolog.logger, channel: security }
    app_bundle.handler.authentication_success_handler:
        class: AppBundle\Handler\AuthenticationSuccessHandler
        arguments: ['@security.http_utils']
        tags:
            - { name: monolog.logger, channel: security }
    app_bundle.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        tags: [twig.extension]
    app_bundle.utils.file_response:
        class: AppBundle\Utils\FileResponse
    app_bundle.utils.page_provider:
        class: AppBundle\Utils\PageProvider
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']